version: '3.7'
services:
  alertmanager:
    image: nexus-dockergroup.dev.idrica.pro/prom/alertmanager:v0.21.0
    volumes:
      - ./alertmanager/alertmanager.yml:/prometheus/alertmanager.yml
      - ./alertmanager/data:/data
    command:
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
    networks:
      - public
    ports:
      - 19093:9093
    
    deploy:
      resources:
        limits:
          memory: 3096MB

networks:
  public:
    external: true

