version: '3.7'
services:
  prometheus:
    image: nexus-dockergroup.dev.idrica.pro/prom/prometheus:v2.22.2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/targets.json:/etc/prometheus/targets.json
      - ./prometheus/targets-platform.json:/etc/prometheus/targets-platform.json
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=30d'
    ports:
      - 9090:9090
    networks:
      - public
    deploy:
      labels:
        - "traefik.docker.network=public"
        - "traefik.web.frontend.rule=Host:api-proxy-emayacloud.go-aigua.com"
        - "traefik.web.port=9090"
      resources:
        limits:
          memory: 3096MB        

networks:
  public:
    external: true
