version: '3.7'

services:
  postgresql_12:
    image: nexus-dockergroup.dev.idrica.pro/postgres:12.8-alpine
    healthcheck:
      test: psql postgres --command "select 1" -U ga_devops
    stop_grace_period: 120s
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 8G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    networks:
      - public

    postgresql_12_exporter:
      image: nexus-dockergroup.dev.idrica.pro/wrouesnel/postgres_exporter
      ports:
        - "9187:9187"
      volumes:
        - DATA_SOURCE_NAME="postgresql://postgres_exporter:36a67f286bcb8a2cf916e63315cf1f84@postgresql_12:5432/goaigua_data?sslmode=disable"
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      deploy:
        resources:
          limits:
            memory: 512M
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 5
          window: 120s
      networks:
        - public

networks:
  public:
    external: true
